### ISSUE TITLE
Name conflict with regards to libjanus and janus

### ISSUE THREAD

**Issue by mickeyl** [dmulholland/ivy#19]
I'm on `macOS 10.14.2` (using python3 from Homebrew). Installed `ivy` via `pip3 install` and get the following error on `ivy init`:

```
% ivy init                                                                                                                                                                         mickey@helios
Traceback (most recent call last):
  File "/usr/local/bin/ivy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ivy/__init__.py", line 67, in main
    cli.parse()
  File "/usr/local/lib/python3.7/site-packages/ivy/cli/__init__.py", line 52, in parse
    parser = janus.ArgParser(helptext, ivy.__version__)
AttributeError: module 'janus' has no attribute 'ArgParser'
```

What can I do?

**Comment by mickeyl** [comment]
Apparently there is a name conflict with janus (https://github.com/aio-libs/janus/).

**Comment by dmulholland** [comment]
Thanks for the report. Virtual environments are the only current solution I know of for this kind of problem:

https://github.com/pypa/virtualenv
