### ISSUE TITLE
Installing ivy fails

### ISSUE THREAD

**Issue by ptdorf** [dmulholland/ivy#2]
```
$ python --version
Python 3.6.2
$ pip install ivy
Collecting ivy
  Using cached ivy-0.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dq/71ckn31n50b_rk9x89xs96fm0000gn/T/pip-build-bYUKtU/ivy/setup.py", line 30, in <module>
        manfile.write(manifest)
    TypeError: write() argument 1 must be unicode, not str

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dq/71ckn31n50b_rk9x89xs96fm0000gn/T/pip-build-bYUKtU/ivy/

```

**Comment by dmulholland** [comment]
That's odd. That's the error you get when you try to install using Python 2. If you look at the line:

    TypeError: write() argument 1 must be unicode, not str

it doesn't make sense in Python 3 as `unicode` and `str` are the same type. Are you sure `pip` isn't using Python 2? In some environments you have to explicitly specify `pip3`.

**Comment by dmulholland** [comment]
Closing this as a Python 2 issue.
